apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  imagePullSecrets:
  - name: dockerhub-creds
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: adam943/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: DB_HOST
          value: "mysql-svc"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db-credentials
              key: db-password

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              name: http

